src/main/java/lt/akademija/entities/Project.java
package lt.akademija.entities;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotBlank;

@Entity
public class Project implements Serializable {

	private static final long serialVersionUID = -2749519293898550077L;

	@Id
	@NotNull
	@NotBlank
	@Size(min = 1, max = 50)
	private String projectName;

	@Size(min = 0, max = 300)
	private String projectDescription;

	@Temporal(TemporalType.DATE)
	private Date projectStartDate;

	@Temporal(TemporalType.DATE)
	private Date projectEndDate;

	public String getProjectName() {
		return projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getProjectDescription() {
		return projectDescription;
	}

	public void setProjectDescription(String projectDescription) {
		this.projectDescription = projectDescription;
	}

	public Date getProjectStartDate() {
		return projectStartDate;
	}

	public void setProjectStartDate(Date projectStartDate) {
		this.projectStartDate = projectStartDate;
	}

	public Date getProjectEndDate() {
		return projectEndDate;
	}

	public void setProjectEndDate(Date projectEndDate) {
		this.projectEndDate = projectEndDate;
	}

}

src/main/java/lt/akademija/entities/Task.java
package lt.akademija.entities;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotBlank;

@Entity
public class Task implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Size(min = 1, max = 30)
	@NotBlank
	private String taskName;
	
	private int taskNumber;
	
	@Temporal(TemporalType.DATE)
	private Date taskCreationDate;
	
	@Temporal(TemporalType.DATE)
	private Date taskCompletionDate;

	public String getTaskName() {
		return taskName;
	}

	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	public int getTaskNumber() {
		return taskNumber;
	}

	public void setTaskNumber(int taskNumber) {
		this.taskNumber = taskNumber;
	}

	public Date getTaskCreationDate() {
		return taskCreationDate;
	}

	public void setTaskCreationDate(Date taskCreationDate) {
		this.taskCreationDate = taskCreationDate;
	}

	public Date getTaskCompletionDate() {
		return taskCompletionDate;
	}

	public void setTaskCompletionDate(Date taskCompletionDate) {
		this.taskCompletionDate = taskCompletionDate;
	}
	
}

src/main/java/lt/akademija/models/ProjectModel.java
package lt.akademija.models;

import java.util.Collection;
import javax.validation.Valid;

import lt.akademija.entities.Project;

public class ProjectModel {

	private Project project;
	@Valid
	private Project currentProject;

	private Collection<Project> projects;

	public void createProject() {
		project = new Project();
	}

	public void nullProject() {
		project = null;
	}

	public Collection<Project> getProjects() {
		return projects;
	}

	public void setProjects(Collection<Project> projects) {
		this.projects = projects;
	}

	public Project getProject() {
		return project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public Project getCurrentProject() {
		return currentProject;
	}

	public void setCurrentProject(Project currentProject) {
		this.currentProject = currentProject;
	}

}

src/main/java/lt/akademija/models/TaskModel.java
package lt.akademija.models;

import java.util.List;

import lt.akademija.entities.Task;

public class TaskModel {
	
	private Task selectedTask;
	private List<Task> tasks;
	
	public Task getSelectedTask() {
		return selectedTask;
	}
	
	public void setSelectedTask(Task selectedTask) {
		this.selectedTask = selectedTask;
	}
	
	public List<Task> getTasks() {
		return tasks;
	}
	
	public void setTasks(List<Task> tasks) {
		this.tasks = tasks;
	}
	
	
}

src/main/java/lt/akademija/controllers/ProjectController.java
package lt.akademija.controllers;

import java.util.Collection;

import lt.akademija.entities.Project;
import lt.akademija.models.ProjectModel;
import lt.akademija.repositories.ProjectDao;

public class ProjectController {

	private ProjectModel projectModel;
	private ProjectDao projectDao;

	public Collection<Project> getProjectList() {
		return projectDao.findAll();
	}

	public String create() {
		projectModel.setCurrentProject(new Project());
		return "project-create";
	}

	public String update(Project project) {
		projectModel.setCurrentProject(project);
		return "project-create";
	}

	public String cancel() {
		projectModel.setCurrentProject(null);
		return "project-list";
	}

	public String save() {
		projectDao.save(projectModel.getCurrentProject());
		return "project-list";
	}

	public Project findByProjectName(String projectName) {
		return projectDao.findByProjectName(projectName);
	}

	public void delete(Project project) {
		projectDao.delete(project);
	}

	public String overview(Project project) {
		projectModel.setCurrentProject(project);
		return "project-overview";
	}

	public ProjectModel getProjectModel() {
		return projectModel;
	}

	public void setProjectModel(ProjectModel projectModel) {
		this.projectModel = projectModel;
	}

	public ProjectDao getProjectDao() {
		return projectDao;
	}

	public void setProjectDao(ProjectDao projectDao) {
		this.projectDao = projectDao;
	}

}

src/main/java/lt/akademija/controllers/TaskController.java
package lt.akademija.controllers;

import java.util.List;

import lt.akademija.entities.Task;
import lt.akademija.models.TaskModel;
import lt.akademija.repositories.TaskRepository;

public class TaskController {

	private TaskRepository taskRepository;
	private TaskModel taskModel;
	
	public TaskRepository getTaskRepository() {
		return taskRepository;
	}
	
	public void setTaskRepository(TaskRepository taskRepository) {
		this.taskRepository = taskRepository;
	}
	
	public TaskModel getTaskModel() {
		return taskModel;
	}
	
	public void setTaskModel(TaskModel taskModel) {
		this.taskModel = taskModel;
	}
	
	public List<Task> getTaskList() {
		return taskRepository.getAllTasks();
	}
	
	public void add() {
		taskModel.setSelectedTask(new Task());
	}
	
	public void update(String taskName) {
		taskModel.setSelectedTask(taskRepository.findByTaskName(taskName));
	}
	
	public void save() {
		taskRepository.save(taskModel.getSelectedTask());
	}
	
	public void delete(Task task) {
		taskRepository.delete(task);
	}
	
	public void cancel() {
		taskModel.setSelectedTask(new Task());
	}
	
	
}

src/main/webapp/project_add.xhtml
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets" template="template.xhtml">

	<ui:define name="page_title">
		Add new project
	</ui:define>

	<ui:define name="content">

		<h:form>
			<p:messages id="messages" showDetail="true" autoUpdate="true"
				closable="true" />
			<p:panel id="basic" header="Add new project"
				style="margin-bottom:20px">
				<h:panelGrid id="grid" columns="3" cellpadding="5">

					<p:outputLabel for="projectName">Project name: </p:outputLabel>
					<p:inputText id="projectName"
						value="#{projectModel.currentProject.projectName}" required="true"
						requiredMessage="Please enter project name"
						validatorMessage="Project name can not be longer than 50 symbols">
						<f:validateBean />
					</p:inputText>
					<p:message for="projectName" />

					<p:outputLabel for="projectDescription">Project description: </p:outputLabel>
					<p:inputTextarea rows="5" cols="20" id="projectDescription"
						value="#{projectModel.currentProject.projectDescription}"
						required="true" requiredMessage="Please enter project description"
						validatorMessage="Project description can not be longer than 300 symbols">
						<f:validateBean />
					</p:inputTextarea>
					<p:message for="projectDescription" />

					<p:outputLabel for="projectStartDate">Project start date: </p:outputLabel>
					<p:calendar id="projectStartDate" pattern="yyyy-MM-dd"
						value="#{projectModel.currentProject.projectStartDate}"
						requiredMessage="Please enter project start date" required="true"
						converterMessage="Use format YYYY-MM-DD">
						<f:convertDateTime pattern="yyyy-MM-dd" />
					</p:calendar>
					<p:message for="projectStartDate" />

					<p:outputLabel for="projectEndDate">Project end date: </p:outputLabel>
					<p:calendar id="projectEndDate" pattern="yyyy-MM-dd"
						value="#{projectModel.currentProject.projectEndDate}"
						requiredMessage="Please enter project end date" required="true"
						converterMessage="Use format YYYY-MM-DD">
						<f:convertDateTime pattern="yyyy-MM-dd" />
					</p:calendar>
					<p:message for="projectEndDate" />

				</h:panelGrid>
			</p:panel>
			<p:commandButton value="Save" action="#{projectController.save()}"
				update="@form" />
			<p:commandButton value="Cancel"
				action="#{projectController.cancel()}" immediate="true" />
		</h:form>

	</ui:define>



</ui:composition>

src/main/webapp/project_list.xhtml
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets" template="template.xhtml">

	<ui:define name="page_title">
		Projects list
	</ui:define>

	<ui:define name="content">
		<h:form>
			<p:dataTable class="table" value="#{projectController.projectList}"
				var="project">
				<f:facet name="header">
       	 			Projects
    			</f:facet>
				<p:column headerText="Project name">
					<p:commandLink action="#{projectController.overview(project)}"
						value="#{project.projectName}"></p:commandLink>
				</p:column>
				<p:column headerText="Project description">
					<h:outputText value="#{project.projectDescription}" />
				</p:column>
				<p:column headerText="Start date">
					<h:outputText value="#{project.projectStartDate}" />
				</p:column>
				<p:column headerText="End date">
					<h:outputText value="#{project.projectEndDate}" />
				</p:column>

				<p:column headerText="Operations">

					<p:commandLink action="#{projectController.overview(project)}"
						value="Overview "></p:commandLink>

					<p:commandLink action="#{projectController.update(project)}"
						value="Update "></p:commandLink>

					<p:commandLink
						actionListener="#{projectController.delete(project)}"
						update="@form" value="Delete " immidiate="true">
						<p:confirm header="Confirmation" message="Are you sure?"
							icon="ui-icon-alert"></p:confirm>
					</p:commandLink>

				</p:column>
			</p:dataTable>

			<p:commandButton action="#{projectController.create}"
				value="Create new project" />


			<p:confirmDialog global="true" showEffect="fade" hideEffect="fade">
				<p:commandButton value="Yes" type="button"
					styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
				<p:commandButton value="No" type="button"
					styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
			</p:confirmDialog>
		</h:form>


	</ui:define>


</ui:composition>

src/main/webapp/project_overview.xhtml
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:c="http://java.sun.com/jsp/jstl/core" template="template.xhtml">

	<ui:define name="page_title">
		Project details
	</ui:define>

	<ui:define name="content">
		<h:form>
			<p:dataTable class="table" value="#{projectModel.currentProject}"
				var="project">
				<f:facet name="header">
        			Project details
    			</f:facet>
				<p:column headerText="Project Name">
					<h:outputText value="#{project.projectName}" />
				</p:column>
				<p:column headerText="Project description">
					<h:outputText value="#{project.projectDescription}" />
				</p:column>
				<p:column headerText="Project Start Date">
					<h:outputText value="#{project.projectStartDate}" />
				</p:column>
				<p:column headerText="Project End Date">
					<h:outputText value="#{project.projectEndDate}" />
				</p:column>

			</p:dataTable>
		</h:form>

		<p:commandButton action="#{projectController.cancel}" value="Go back" />


	</ui:define>


</ui:composition>

src/main/webapp/template.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
      
	<h:head>
  		<title>TATA project management system 
  			<ui:insert name="page_title"></ui:insert>
  		</title>
	</h:head>

	<h:body>
	
		<div class="context">
			<ui:insert name="content"/>
		</div>
  
	</h:body>
</html>